### 1- What is NumPy array? 
NumPy is the basis of Pandas and many other packages. What makes NumPy such an incredible package is its data type (ndarray). ndarray stands for n-dimensional array, which basically looks like a Python list. However, it is a lot faster than a regular Python list. A Python list can contain different kinds of data types, such as integers, strings, Boolean, True, False and even lists. On the other hand, NumPy arrays can hold only one type of data, and therefore doesn't have to check the type of data type for every single element of the array when it is doing the computations. This feature makes NumPy a great tool for data science research and projects.

Before we get started, let's check the version of NumPy and Python.

In [1]:
# import numpy
import numpy as np

# sys was imported to check the python version
import sys 

# check the version of python and numpy
print('NumPy version:', np.__version__)
print('Python version',sys.version)

NumPy version: 1.15.4
Python version 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]


### 2- How to create NumPy arrays

There are many ways to create arrays in NumPy. We will take a look at a few of them here.

In [2]:
# create one dimensional numpy array
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# Array of zeros
np.zeros(3)

array([0., 0., 0.])

In [4]:
# Array of 1s
np.ones(3)

array([1., 1., 1.])

In [5]:
# array of 3 random integers between 1 and 10
np.random.randint(1,10, 3)

array([2, 2, 4])

In [6]:
# create 2-Dimensional array
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# create 3x4 array values between 0 and 1
np.random.random((3,4))

array([[0.74631513, 0.94092556, 0.85140379, 0.8000905 ],
       [0.61230401, 0.0962323 , 0.75257431, 0.81897588],
       [0.88642224, 0.72729327, 0.91059061, 0.4533184 ]])

In [9]:
# adding values 
a=[1,7,8,9]
a = np.append(a, 4)


array([1, 7, 8, 9, 4])

In [25]:
# print the shape and dimension of arrays
b=np.array([[2,3,5,6],[1,2,9,0],[1,3,0,7]])
print("Shape of a:", np.shape(a))
print("Shape of b:", np.shape(b))

print('Dimension of a:', np.ndim(a))
print('Dimension of b:', np.ndim(b))

Shape of a: (5,)
Shape of b: (3, 4)
Dimension of a: 1
Dimension of b: 2


In [26]:
#  number of elements in the arrays
print('Number of elements in a:', np.size(a))
print('Number of elements in b:', np.size(b))

Number of elements in a: 5
Number of elements in b: 12


### 3- Indexing and Fancy Indexing

In [27]:
# a is 1D array, we created before
a

array([1, 7, 8, 9, 4])

In [28]:
# b is 2D array created in a previous cell
b

array([[2, 3, 5, 6],
       [1, 2, 9, 0],
       [1, 3, 0, 7]])

In [29]:
# get the first element of a 
# these 2 print statements results the same
print(a[0])
print(a[-5])

1
1


In [30]:
# get the last element of a 
# these 2 print statements results the same
print(a[-1])
print(a[4])

4
4


In [31]:
# get the first row of b
# these 2 print statements results the same
print(b[0]) 
print(b[0,1])

[2 3 5 6]
3


In [32]:
# get the second column of b
b[:,1]

array([3, 2, 3])

In [38]:
# to understand the fancy indexing better. we will create 2 new arrays. 
x = np.array(['a', 'b', 'c'])
y = np.array([['d','e','f'], 
              ['g', 'h', 'k']])

print(x)
print(y)

['a' 'b' 'c']
[['d' 'e' 'f']
 ['g' 'h' 'k']]


In [39]:
# fancy indexing on 1D array
# get the value of c in array x
ind = [2]
x[ind]

array(['c'], dtype='<U1')

In [40]:
# fancy indexing on 2D array
# get the values  e,h in array y
ind2 = [[0,1],[1]]
y[ind2]

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  after removing the cwd from sys.path.


array(['e', 'h'], dtype='<U1')

### 4- Slicing
###### use : for slicing

In [41]:
# create an array integer from 1 to 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# get the first two elements of X 
X[:2]

array([1, 2])

In [43]:
# get the number 3,4 and 5 
X[2:5]

array([3, 4, 5])

In [25]:
# get the odd numbers 
X[::2]

array([1, 3, 5, 7, 9])

In [68]:
#Reverse the Array
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [26]:
# get the even numbers
X[1::2]

array([ 2,  4,  6,  8, 10])

In [27]:
# create 2D array
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# get the first and second row
Y[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# get the second and third column
Y[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [30]:
#get the element of 5 and 6
Y[1,1:]

array([5, 6])

### 5- Universal Functions(Ufuncs)

##### press TAB after np. to see list of available ufuncs. np.{TAB}

Allow fast computation in NumPy arrays.

In [44]:
# use the same array we created earlier
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#find the maximum element of X
np.max(X)

10

In [46]:
#mean of values in the X
np.mean(X)

5.5

In [47]:
# get the 4th power of each value
np.power(X, 4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
       10000], dtype=int32)

In [48]:
# trigonometric functions 
print(np.sin(X))
print(np.tan(X))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [49]:
# x2 + y2 = 1
np.square(np.sin(X)) + np.square(np.cos(X))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
# same rules applies for 2D array
Y= np.array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [54]:
np.multiply(Y, 2)

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [55]:
# split Y into 3 subarrays
np.split(Y, 3)

[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]

### 6- Broadcasting

 Broadcasting is being able to use ufuncs and many other operations on different size of arrays

In [56]:
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# add 5 to each element
X + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
# or 
np.add(X, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 7- Sorting, Comparising and Masking

In [59]:
# create array of 10 elements between 1 and 5
x = np.random.randint(1,5, 10)
x

array([3, 4, 3, 3, 3, 4, 3, 4, 3, 4])

In [60]:
# create (3,3) size of array elements from 1 and 5
y = np.random.randint(1,5, (3,3))
y

array([[2, 1, 3],
       [2, 4, 2],
       [4, 2, 3]])

In [61]:
# sort elements in array x
np.sort(x)

array([3, 3, 3, 3, 3, 3, 4, 4, 4, 4])

In [62]:
y

array([[2, 1, 3],
       [2, 4, 2],
       [4, 2, 3]])

In [63]:
# sort values along the rows
np.sort(y, axis=0)

array([[2, 1, 2],
       [2, 2, 3],
       [4, 4, 3]])

In [64]:
# sort values along the columns
np.sort(y, axis=1)

array([[1, 2, 3],
       [2, 2, 4],
       [2, 3, 4]])

In [65]:
# == , !=, < , >, >=, <= operations on arrays
#This returns a boolean
x > 3

array([False,  True, False, False, False,  True, False,  True, False,
        True])

In [66]:
# use masking feature to get the values of comparisons
x[x>3]

array([4, 4, 4, 4])

In [67]:
# more example
x[(x <= 3) & (x>1)]

array([3, 3, 3, 3, 3, 3])